apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-app
  namespace: config-secret-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
      - name: app
        image: busybox
        command:
          - sh
          - -c
          - |
            env
            sleep 3600
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: db-secret
