apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pe-validating
webhooks:
- name: validate.platform.demo
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
  clientConfig:
    service:
      name: pe-webhook
      namespace: platform-demo
      port: 8443
      path: /validate
    caBundle: "QmdrcWhraUc5dzBCQVFzRkFEQW4NCk1TVXdJd1lEVlFRRERCeHdaUzEzWldKb2IyOXJMbkJzWVhSbWIzSnRMV1JsYlc4dWMzWmpNQjRYRFRJMU1USXoNCk1UQTRNamd4TlZvWERUSTJNVEl6TVRBNE16Z3hORm93SnpFbE1DTUdBMVVFQXd3Y2NHVXRkMlZpYUc5dmF5NXcNCmJHRjBabTl5YlMxa1pXMXZMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUINCkFPQ1FMMStncjl0dEVrNzZUMmczMWV6a05aK3ZWNlZ6ZnR0d241NDNRRC9KampXNGs5TUF3cjRCbHd1cnpRWDYNCnIwV2d3em5ZNlRiMjVqb0d0WjE5czFEM2tuMkNySkg0bmV1TksxMHB3UTgvakxQM1FTdWVuTUVKSndmRzRwYnENCk5WaEdTam9ZaHVTMnVJVzdkT2tUKzU0SHV6UUlXTXJPMFJ4QmtrYndYRkhwYUM3SG5OV2MyeWFFU0ZoaXhVVHcNCkFzL2ZsR1BtRVNmMnJhMlVvM2RsNEZXS3NwVGlzQmJ4N2dOQlRrMkkvd0dYYWRWU3dWZ2FYSHlWTGVMMkxEUHENCm9mY1hOMVJpWVIrVTNMVjFrQzdscG5yaUNGWEpOT3poZlN3Y0NLeXRFWDd5K3Rib0dBRWJ1Qlc0bXVxU0wvSnYNCjh2Nk9zQ0NteTJDaERmV251M2hqVnFVQ0F3RUFBYU41TUhjd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWQNCkpRUVdNQlFHQ0NzR0FRVUZCd01DQmdnckJnRUZCUWNEQVRBbkJnTlZIUkVFSURBZWdoeHdaUzEzWldKb2IyOXINCkxuQnNZWFJtYjNKdExXUmxiVzh1YzNaak1CMEdBMVVkRGdRV0JCU205Yyt2UWxoMjV1UXovSkV3cmF6T0ZFd3INClhUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrZmRCS1FaSUdzblM0UDhISDlLUEdQRUtNenQrK2FHME51ZjMNCjZlUVBzWWlmUVFGSTBKVG16aVlidkJmNHRqa2pmazllM3l6QnhsUjJWZTI3ZGJsY29PZVVKZU1xU29Ra0pxcDQNCmsvVDdReE9Dc1B1Zm5yR0dWSFB3STdIQjBFNVpxVTlOb1JXWU5ZcDhjcURZUysrNW85QUJmSlFHNDJhSWxuTE0NCmgvcGJETEQ1V1lhK0xTVWQrMWdVRG5neDBwZEJWZ1JObXNGa21sT2JyRlByTmhEc3AvL2kzV0xMTnBDUGd0NmsNCkEwOTlJS0pGNDkreW1lMTJWV1hTa1hjR2Nub3dxMkZ3Y25hRWFoRktHTyswdHFtNXRCLzlKNFB2ZlZKY1I2bVENCmQrOUxpVEU0aTdRUjd6eDlyRDBOZ0ZPdlAxSkc0dDVJY0lPMVdLRDNJNlhDQTBja1JnPT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg=="
  admissionReviewVersions: ["v1"]
  sideEffects: None
 